# Generated by Django 5.2.16 on 2026-07-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finding',
            options={'ordering': [models.Case(models.When(severity='critical', then=0), models.When(severity='high', then=1), models.When(severity='medium', then=2), models.When(severity='low', then=3), default=4, output_field=models.IntegerField()), 'rule_id', 'id']},
        ),
        migrations.AddField(
            model_name='audit',
            name='configuration_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
