# Generated by Django 5.2.16 on 2026-07-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_finding_options_audit_configuration_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='category_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='audit',
            name='score_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
